### ISSUE TITLE
Add guides section

### ISSUE THREAD

**Issue by sean-clayton** [13vaults/13vaults.com#18]
These two I think are absolutely crucial to get in:
- New Player guide
- New GM guide

Here are some more ideas:
- Class build guides
- Icon rolls and how to use them
- More examples of One Unique Things
- More examples of backgrounds
- Building memorable encounters
- Tiers of play (including what to expect at each tier)
- Building adventures or campaigns around monsters (Dragons, Demons, etc)
- More Icons for your games
- Customizing Icons
- More feats for your games (general, maybe also feats specifically for martial characters and spellcasters?)
- 13th Age for D&D 5e Players and DMs
- 13th Age for Pathfinder 2e Players and GMs
- Making a Hack for 13th Age
- The Math Behind 13th Age
- Multiclassing for fun and profit (and these weird tricks to avoid doing)
- How to create homebrew classes for 13th Age
- How to create homebrew races for 13th Age
- How to create homebrew magic items for 13th Age
- New systems to make your 13th Age games better (eg. BitD clocks, Dungeonworld Fronts)
- Pacing with the four battle day
- Icon Alternatives (icons as factions, icons as weaker individuals that get replaced by their bosses as you level, gloranthan runes, stranger variants like eberron dragonmarks, icons as gods etc)
- How to play 13th Age Online (VTTs, online tools, etc)

**Comment by clarkkristofor** [comment]
Love this idea. Thanks for your initiative. I can write. I can't code. So guides are probably where I can help the most. [Here's a few](https://superclark.net/52ec83d1db0f42b1bc61507509690d6e?v=87f73b99ab6d4ff481a0d350a1fbe31f) "guides" I wrote already. I'm on Discord clarkkristofor#7362

**Comment by sean-clayton** [comment]
@clarkkristofor This is great stuff :) Exactly the kind of things that would be perfect for the vaults!

When I get around to adding the guides section I'll be sure to inquire some more 😸

**Comment by clarkkristofor** [comment]
@sean-clayton sounds good.
