### ISSUE TITLE
Add site search functionality

### ISSUE THREAD

**Issue by sean-clayton** [13vaults/13vaults.com#22]
Two possible methods for the initial search:

1. Just make a rudimentary offline search by collecting all the headings and titles of everything, associate URLs to those, and then do all the fuzzy searching on the client.
2. Use [Algolia's free tier](https://www.algolia.com/pricing/). I don't think we'll exceed it _anytime_ soon, and if we do, we probably would qualify for [their open source discount](https://www.algolia.com/for-open-source/)

**Comment by MisterCheesy** [comment]
I need this.
